### ISSUE TITLE
Is it possible to achieve a large-scale indoor navigation function by providing a model with a video of an indoor space that can be analyzed based on the indoor layout, and then inputting a picture and the destination I want to reach, so that it can recognize my location and perform path planning and navigation? How many VRAMs are needed and how long will they be open sourced? I'm looking forward to it

### ISSUE THREAD

**Issue by libai-lab** [hustvl/Senna#1]
Is it possible to achieve a large-scale indoor navigation function by providing a model with a video of an indoor space that can be analyzed based on the indoor layout, and then inputting a picture and the destination I want to reach, so that it can recognize my location and perform path planning and navigation? How many VRAMs are needed and how long will they be open sourced? I'm looking forward to it

**Comment by xinggangw** [comment]
Yes, it is very possible. Applying Senna for indoor navigation faces the problem of lacking training data. In auto drive, we have a huge amount of data for training. The code and models of Senna will be released after the CVPR deadline.
