### ISSUE TITLE
eval_plan_qa.json

### ISSUE THREAD

**Issue by PG-Wang** [hustvl/Senna#13]
Thanks for your excellent job!!!!!
When I follow your instruction to generate QA data, it take around 160s for one iteration on 2 A100, is this normal? If is real, OMG, it takes so long time to generate.
Could you  please share your eval_plan_qa.json with us?

**Comment by Matilda-de** [comment]
Hello, did you solve this issue?

**Comment by Matilda-de** [comment]
> Thanks for your excellent job!!!!! When I follow your instruction to generate QA data, it take around 160s for one iteration on 2 A100, is this normal? If is real, OMG, it takes so long time to generate. Could you please share your eval_plan_qa.json with us?

Hello, did you solve this issue?

**Comment by PG-Wang** [comment]
no, it takes too long to generate the nuscenes_qa_json, i just train and test the algorithm with nuscenes_mini

**Comment by rb93dett** [comment]
Yes, the generation speed for QAs like scene description is relatively slow. You can try using 8-bit or 4-bit inference to speed up the generation. Besides, if your goal is solely meta-action planning, you can generate only meta-action planning QAs and fine-tune on the provided pretrained weights. This approach does not involve inference with LLaVA-Next-34B, so the speed will be much faster.

**Comment by PG-Wang** [comment]
Thank you. Yes, I notice that the meta-action planning QAs is generated just by GT-annotation with nuScenes.
