### ISSUE TITLE
senna_nusc_data_converter.py error

### ISSUE THREAD

**Issue by wolf943134497** [hustvl/Senna#18]
hi @rb93dett  Thanks for your great works!
I encountered an error，in line 316 of senna_nusc_data_converter.py.
<img width="369" alt="image" src="https://github.com/user-attachments/assets/c55831b3-7e56-428e-8474-8960b88c2a5e" />

nusc.category does not have the key "index "

How can I solve this problem？ Thanks

**Comment by xingaoli** [comment]
I met the same problem, can you tell me how you solved it? thx.

**Comment by wolf943134497** [comment]
download nusc lidarseg dataset

**Comment by Cloud-li1** [comment]
> download nusc lidarseg dataset

It works for me. Thanks a lot.

**Comment by FANGDUI0211** [comment]
> nusc lidarseg dataset

In what position in the directory should set  nusc lidarseg dataset? thx!

**Comment by hypez66** [comment]
> > nusc lidarseg dataset
> 
> In what position in the directory should set nusc lidarseg dataset? thx!

Have you figure out where to put the lidarseg dataset? Thanks!
