### ISSUE TITLE
question about meta-action encoder

### ISSUE THREAD

**Issue by TmacTmac1992** [hustvl/Senna#4]
Thanks for your awesome work! Could you please let me know if the meta-action encoder uses an encoder similar to CLIP? Also, how does it align with ego_query in the trajectory space?

**Comment by rb93dett** [comment]
Since meta actions belong to a fixed set, each meta action corresponds to an embedding query. During the training of Senna-E2E, the embedding parameters corresponding to each meta action are updated simultaneously, achieving alignment with the feature space of the end-to-end model.

**Comment by TmacTmac1992** [comment]
> Since meta actions belong to a fixed set, each meta action corresponds to an embedding query. During the training of Senna-E2E, the embedding parameters corresponding to each meta action are updated simultaneously, achieving alignment with the feature space of the end-to-end model.

Thanks for your reply. Now I understand, the meta actions are predefined fixed set actions, which can be alignment with the feature space of end-to-end model. I was wondering if the meta actions are just some text descriptions, how to encode the text and align with the feature space of trajectory.
