### ISSUE TITLE
If we want to achieve full scene understanding, what is the approximate cost of the vlm annotation solution

### ISSUE THREAD

**Issue by hunkyu** [hustvl/Senna#7]
If we want to achieve full scene understanding, what is the approximate cost of the vlm annotation solution? Can you provide more information on the process of training vlm?

**Comment by rb93dett** [comment]
Hi, could you clarify what you mean by annotation cost? Are you referring to GPU hour costs? Additionally, the paper includes an introduction to the VLM training process in Section III.D. If you have any specific questions, feel free to let me know.
