### ISSUE TITLE
Considerations for Choosing Vicuna-v1.5-7b as the LLM Model

### ISSUE THREAD

**Issue by xiaodongww** [hustvl/Senna#8]
Hi,

I have a question regarding the choice of the LLM model used in this project. Could you please explain why Vicuna-v1.5-7b was selected? Were there any specific considerations or factors that influenced this decision?

Thank you!

**Comment by rb93dett** [comment]
Using Vicuna-v1.5-7b is based on empirical results. We found that it delivers the best performance in driving scenarios.
