### ISSUE TITLE
Requires for details of python environment 

### ISSUE THREAD

**Issue by xiaodongww** [hustvl/Senna#9]
Hi, thanks for your great work. 

I just met a pakcage version conflict problem when installing python env.
Would you mind exporting all package versions to requirements.txt? Like this:
pip freeze > requirements_pip.txt 
conda list -e > requirements_conda.txt

In this way I can install the correct versions of all packages.

Thanks!

**Comment by rb93dett** [comment]
Hi, The current [requirements.txt](https://github.com/hustvl/Senna/blob/main/requirements.txt) is already generated using `pip freeze > requirements_pip.txt`. You can share the conflicts you've encountered, and I'll help you analyze them.

**Comment by xiaodongww** [comment]
Thanks for your help, I have fixed the installing problem.
